spring.application.name=business-process-automation

# ===============================
# Active Profile
# ===============================
spring.profiles.active=dev

# ===============================
# JPA Common Config
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
